'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { ApiRequestError, apiFetch } from '../lib/api-client';
import { adminApi, type AdminSession } from '../lib/admin-data-source';
import { useAuth } from './auth-provider';
import { GoogleSignInButton } from './google-sign-in-button';
import styles from './admin-professional-console.module.css';

type Metrics={customers:number;open_quotes:number;accepted_quotes:number;issued_invoices:number;overdue_invoices:number;billed_eur:number;collected_eur:number;pending_eur:number};
type Customer={id:string;workspace_id:string;workspace_name:string;kind:string;display_name:string;legal_name:string|null;tax_id:string|null;phone:string|null;email:string|null;notes:string|null;active:boolean;work_count:number;quote_count:number;invoice_count:number;charged_eur:number;collected_eur:number;pending_eur:number};
type Quote={id:string;workspace_id:string;workspace_name:string;customer_party_id:string;customer_name:string;quote_number:string|null;title:string;issued_on:string|null;valid_until:string|null;status:string;subtotal_eur:number;tax_eur:number;total_eur:number};
type Invoice={id:string;workspace_id:string;workspace_name:string;customer_party_id:string;customer_name:string;invoice_number:string|null;issued_on:string|null;due_on:string|null;status:string;subtotal_eur:number;tax_eur:number;total_eur:number;collected_eur:number;pending_eur:number;notes:string|null};
type CustomerDetail={customer:Customer;sites:Array<{id:string;name:string;active:boolean}>;works:Array<{id:string;occurred_on:string;title:string;charge_eur:number|null;payment_status:string}>;quotes:Quote[];invoices:Invoice[];collections:Array<{id:string;collected_on:string;amount_eur:number;work_title:string}>};
type Draft={display_name:string;legal_name:string;tax_id:string;phone:string;email:string;notes:string;active:boolean};
type Tab='customers'|'quotes'|'invoices';
const money=(v:number|null|undefined)=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(v??0);
const canEdit=(s:AdminSession|null)=>s?.platform_access.role==='admin'||s?.platform_access.role==='super_admin';
const draftFrom=(c:Customer):Draft=>({display_name:c.display_name,legal_name:c.legal_name??'',tax_id:c.tax_id??'',phone:c.phone??'',email:c.email??'',notes:c.notes??'',active:c.active});

export function AdminProfessionalConsole(){
 const auth=useAuth();const[session,setSession]=useState<AdminSession|null>(null);const[loading,setLoading]=useState(true);const[denied,setDenied]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[msg,setMsg]=useState<string|null>(null);const[metrics,setMetrics]=useState<Metrics|null>(null);const[customers,setCustomers]=useState<Customer[]>([]);const[quotes,setQuotes]=useState<Quote[]>([]);const[invoices,setInvoices]=useState<Invoice[]>([]);const[tab,setTab]=useState<Tab>('customers');const[q,setQ]=useState('');const[selected,setSelected]=useState<string|null>(null);const[detail,setDetail]=useState<CustomerDetail|null>(null);const[draft,setDraft]=useState<Draft|null>(null);
 const editable=canEdit(session);
 const load=useCallback(async()=>{const p=new URLSearchParams({limit:'300'});if(q.trim())p.set('q',q.trim());const[overview,c,qu,inv]=await Promise.all([apiFetch<{metrics:Metrics}>('/api/v1/admin/professional/overview'),apiFetch<{customers:Customer[]}>(`/api/v1/admin/professional/customers?${p}`),apiFetch<{quotes:Quote[]}>(`/api/v1/admin/professional/quotes?${p}`),apiFetch<{invoices:Invoice[]}>(`/api/v1/admin/professional/invoices?${p}`)]);setMetrics(overview.metrics);setCustomers(c.customers);setQuotes(qu.quotes);setInvoices(inv.invoices);setSelected(x=>x&&c.customers.some(v=>v.id===x)?x:c.customers[0]?.id??null);},[q]);
 const hydrate=useCallback(async()=>{if(auth.status!=='authenticated')return;setLoading(true);setError(null);try{setSession(await adminApi.session());await load();}catch(e){if(e instanceof ApiRequestError&&e.status===403)setDenied(true);else setError('No se ha podido cargar Profesional.');}finally{setLoading(false);}},[auth.status,load]);
 useEffect(()=>{if(auth.status==='authenticated')void hydrate();if(auth.status==='anonymous')setLoading(false);},[auth.status,hydrate]);
 useEffect(()=>{if(!selected){setDetail(null);setDraft(null);return;}let cancel=false;void apiFetch<CustomerDetail>(`/api/v1/admin/professional/customers/${selected}`).then(r=>{if(!cancel){setDetail(r);setDraft(draftFrom(r.customer));}}).catch(()=>{if(!cancel)setError('No se ha podido cargar el cliente.');});return()=>{cancel=true;};},[selected]);
 const customerRows=useMemo(()=>customers,[customers]);
 async function saveCustomer(){if(!detail||!draft||!editable)return;setBusy(true);setError(null);try{const r=await apiFetch<{customer:Customer}>(`/api/v1/admin/professional/customers/${detail.customer.id}`,{method:'PATCH',body:JSON.stringify({display_name:draft.display_name.trim(),legal_name:draft.legal_name.trim()||null,tax_id:draft.tax_id.trim()||null,phone:draft.phone.trim()||null,email:draft.email.trim()||null,notes:draft.notes.trim()||null,active:draft.active})});setDetail({...detail,customer:r.customer});setDraft(draftFrom(r.customer));setMsg('Cliente actualizado y auditado.');await load();}catch{setError('No se ha podido actualizar el cliente.');}finally{setBusy(false);}}
 async function quoteStatus(id:string,status:string){setBusy(true);setError(null);try{await apiFetch(`/api/v1/admin/professional/quotes/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});setMsg('Estado del presupuesto actualizado.');await load();if(selected)setDetail(await apiFetch<CustomerDetail>(`/api/v1/admin/professional/customers/${selected}`));}catch(e){setError(e instanceof ApiRequestError&&e.status===409?'La transición no está permitida por el flujo comercial.':'No se ha podido actualizar el presupuesto.');}finally{setBusy(false);}}
 async function invoiceStatus(invoice:Invoice,status:'issued'|'void'){setBusy(true);setError(null);try{const payload=status==='issued'?{status,invoice_number:invoice.invoice_number,issued_on:invoice.issued_on}:{status};await apiFetch(`/api/v1/admin/professional/invoices/${invoice.id}`,{method:'PATCH',body:JSON.stringify(payload)});setMsg(status==='void'?'Factura anulada con trazabilidad.':'Factura emitida.');await load();if(selected)setDetail(await apiFetch<CustomerDetail>(`/api/v1/admin/professional/customers/${selected}`));}catch(e){setError(e instanceof ApiRequestError&&e.status===400?'Para emitir se requiere número y fecha de factura.':e instanceof ApiRequestError&&e.status===409?'La factura está anulada y es inmutable.':'No se ha podido actualizar la factura.');}finally{setBusy(false);}}
 if(auth.status==='loading'||loading)return <main className={styles.gate}>Cargando Profesional…</main>;if(auth.status==='anonymous')return <main className={styles.gate}><div><h1>Profesional protegido</h1><GoogleSignInButton/></div></main>;if(denied)return <main className={styles.gate}>Acceso restringido.</main>;if(!session)return <main className={styles.gate}>{error}</main>;
 return <main className={styles.shell}><header className={styles.hero}><div><span>ADMIN · PROFESIONAL</span><h1>Clientes, presupuestos y facturas</h1><p>Soporte comercial transversal con importes financieros protegidos.</p></div><nav><Link href="/admin/trabajos">Trabajos</Link><Link href="/admin/documentos">Documentos</Link><Link href="/admin/operaciones">Operaciones</Link></nav></header>{msg?<div className={styles.ok}>{msg}</div>:null}{error?<div className={styles.err}>{error}</div>:null}
 {metrics?<section className={styles.metrics}><article>Clientes<strong>{metrics.customers}</strong></article><article>Presupuestos abiertos<strong>{metrics.open_quotes}</strong></article><article>Facturas emitidas<strong>{metrics.issued_invoices}</strong></article><article>Facturación<strong>{money(metrics.billed_eur)}</strong></article><article>Cobrado<strong>{money(metrics.collected_eur)}</strong></article><article>Pendiente<strong>{money(metrics.pending_eur)}</strong></article><article>Vencidas<strong>{metrics.overdue_invoices}</strong></article></section>:null}
 <section className={styles.toolbar}><div><button className={tab==='customers'?styles.active:''} onClick={()=>setTab('customers')}>Clientes</button><button className={tab==='quotes'?styles.active:''} onClick={()=>setTab('quotes')}>Presupuestos</button><button className={tab==='invoices'?styles.active:''} onClick={()=>setTab('invoices')}>Facturas</button></div><div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar cliente, documento, workspace…"/><button onClick={()=>void load()}>Buscar</button></div></section>
 {tab==='customers'?<section className={styles.grid}><aside className={styles.panel}><div className={styles.list}>{customerRows.map(c=><button key={c.id} className={selected===c.id?styles.selected:''} onClick={()=>setSelected(c.id)}><strong>{c.display_name}</strong><span>{c.workspace_name} · {c.invoice_count} facturas</span><small>{money(c.pending_eur)} pendiente · {c.active?'activo':'inactivo'}</small></button>)}</div></aside><section className={styles.panel}>{detail&&draft?<><div className={styles.head}><div><span>Cliente</span><h2>{detail.customer.display_name}</h2><p>{detail.customer.workspace_name}</p></div><b>{detail.customer.active?'Activo':'Inactivo'}</b></div><div className={styles.form}><label>Nombre<input disabled={!editable} value={draft.display_name} onChange={e=>setDraft({...draft,display_name:e.target.value})}/></label><label>Razón social<input disabled={!editable} value={draft.legal_name} onChange={e=>setDraft({...draft,legal_name:e.target.value})}/></label><label>NIF/CIF<input disabled={!editable} value={draft.tax_id} onChange={e=>setDraft({...draft,tax_id:e.target.value})}/></label><label>Teléfono<input disabled={!editable} value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></label><label>Email<input disabled={!editable} value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></label><label className={styles.full}>Notas<textarea disabled={!editable} rows={3} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><label className={styles.check}><input disabled={!editable} type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/> Cliente activo</label></div>{editable?<button className={styles.primary} disabled={busy||!draft.display_name.trim()} onClick={()=>void saveCustomer()}>Guardar cliente</button>:null}<div className={styles.cards}><article>Trabajos<strong>{detail.customer.work_count}</strong></article><article>Presupuestos<strong>{detail.customer.quote_count}</strong></article><article>Facturas<strong>{detail.customer.invoice_count}</strong></article><article>Pendiente<strong>{money(detail.customer.pending_eur)}</strong></article></div><h3>Últimas facturas</h3>{detail.invoices.slice(0,6).map(i=><div className={styles.row} key={i.id}><span>{i.invoice_number??'Borrador'} · {i.status}</span><strong>{money(i.total_eur)} · {money(i.pending_eur)} pendiente</strong></div>)}</>:<p>Selecciona un cliente.</p>}</section></section>:null}
 {tab==='quotes'?<section className={styles.panel}><div className={styles.tableWrap}><table><thead><tr><th>Presupuesto</th><th>Cliente</th><th>Workspace</th><th>Estado</th><th>Total</th><th>Acciones</th></tr></thead><tbody>{quotes.map(x=><tr key={x.id}><td>{x.quote_number??'—'}<small>{x.title}</small></td><td>{x.customer_name}</td><td>{x.workspace_name}</td><td>{x.status}</td><td>{money(x.total_eur)}</td><td>{editable&&x.status!=='converted'?<div className={styles.actions}><button disabled={busy} onClick={()=>void quoteStatus(x.id,'sent')}>Enviado</button><button disabled={busy} onClick={()=>void quoteStatus(x.id,'accepted')}>Aceptar</button><button disabled={busy} onClick={()=>void quoteStatus(x.id,'rejected')}>Rechazar</button><button disabled={busy} onClick={()=>void quoteStatus(x.id,'expired')}>Caducar</button></div>:<span>Inmutable</span>}</td></tr>)}</tbody></table></div></section>:null}
 {tab==='invoices'?<section className={styles.panel}><div className={styles.tableWrap}><table><thead><tr><th>Factura</th><th>Cliente</th><th>Estado</th><th>Total</th><th>Cobrado</th><th>Pendiente</th><th>Acciones</th></tr></thead><tbody>{invoices.map(i=><tr key={i.id}><td>{i.invoice_number??'Sin número'}<small>{i.issued_on??'Sin emitir'}</small></td><td>{i.customer_name}<small>{i.workspace_name}</small></td><td>{i.status}</td><td>{money(i.total_eur)}</td><td>{money(i.collected_eur)}</td><td>{money(i.pending_eur)}</td><td>{editable&&i.status!=='void'?<div className={styles.actions}>{i.status==='draft'?<button disabled={busy||!i.invoice_number||!i.issued_on} onClick={()=>void invoiceStatus(i,'issued')}>Emitir</button>:null}<button disabled={busy} onClick={()=>void invoiceStatus(i,'void')}>Anular</button></div>:<span>Inmutable</span>}</td></tr>)}</tbody></table></div></section>:null}
 </main>;
}
