'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { ApiRequestError, apiFetch } from '../lib/api-client';
import { adminApi, type AdminSession } from '../lib/admin-data-source';
import { useAuth } from './auth-provider';
import { GoogleSignInButton } from './google-sign-in-button';
import styles from './admin-documents-console.module.css';

type Doc={id:string;workspace_name:string;kind:string;title:string;status:'active'|'archived';original_filename:string|null;mime_type:string|null;byte_size:number|null;upload_status:string|null;integrity_status:string|null;latest_ocr_status:string|null;latest_ocr_provider:string|null;latest_ocr_error_code:string|null;latest_ocr_error_message:string|null;links_count:number;created_at:string};
type Counts={active:number;archived:number;upload_failed:number;ocr_failed:number;ocr_pending:number};
type Detail={document:Doc;versions:Array<{id:string;version_no:number;original_filename:string;mime_type:string;byte_size:number;upload_status:string;integrity_status:string;uploaded_at:string|null;created_at:string}>;links:Array<{id:string;field_id:string|null;domain_type:string|null;domain_record_id:string|null;relation:string}>;ocr_runs:Array<{id:string;document_version_id:string;provider:string;provider_version:string|null;status:string;confidence:number|null;error_code:string|null;error_message:string|null;created_at:string;completed_at:string|null}>;extractions:Array<{id:string;document_type:string;schema_version:number;status:string;created_at:string;completed_at:string|null}>};
function canEdit(s:AdminSession|null){return s?.platform_access.role==='admin'||s?.platform_access.role==='super_admin';}
function bytes(v:number|null){if(v==null)return'—';if(v<1024)return`${v} B`;if(v<1048576)return`${(v/1024).toFixed(1)} KB`;return`${(v/1048576).toFixed(1)} MB`;}
export function AdminDocumentsConsole(){
 const auth=useAuth();const[session,setSession]=useState<AdminSession|null>(null);const[loading,setLoading]=useState(true);const[denied,setDenied]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);const[docs,setDocs]=useState<Doc[]>([]);const[counts,setCounts]=useState<Counts>({active:0,archived:0,upload_failed:0,ocr_failed:0,ocr_pending:0});const[selected,setSelected]=useState<string|null>(null);const[detail,setDetail]=useState<Detail|null>(null);const[q,setQ]=useState('');const[ocr,setOcr]=useState('all');
 const load=useCallback(async()=>{const p=new URLSearchParams({limit:'300',document_status:'all',upload_status:'all',ocr_status:ocr});if(q.trim())p.set('q',q.trim());const r=await apiFetch<{documents:Doc[];counts:Counts}>(`/api/v1/admin/documents?${p}`);setDocs(r.documents);setCounts(r.counts);setSelected((x)=>x&&r.documents.some(d=>d.id===x)?x:r.documents[0]?.id??null);},[q,ocr]);
 const hydrate=useCallback(async()=>{if(auth.status!=='authenticated')return;setLoading(true);setError(null);try{setSession(await adminApi.session());await load();}catch(e){if(e instanceof ApiRequestError&&e.status===403)setDenied(true);else setError('No se ha podido cargar Documentos/OCR.');}finally{setLoading(false);}},[auth.status,load]);
 useEffect(()=>{if(auth.status==='authenticated')void hydrate();if(auth.status==='anonymous')setLoading(false);},[auth.status,hydrate]);
 useEffect(()=>{if(!selected){setDetail(null);return;}let cancelled=false;void apiFetch<Detail>(`/api/v1/admin/documents/${selected}`).then(r=>{if(!cancelled)setDetail(r);}).catch(()=>{if(!cancelled)setError('No se ha podido cargar el detalle documental.');});return()=>{cancelled=true;};},[selected]);
 async function setStatus(status:'active'|'archived'){if(!detail||!canEdit(session))return;setBusy(true);setError(null);try{await apiFetch(`/api/v1/admin/documents/${detail.document.id}/status`,{method:'PATCH',body:JSON.stringify({status})});setMessage(status==='archived'?'Documento archivado.':'Documento restaurado.');await load();setDetail(await apiFetch<Detail>(`/api/v1/admin/documents/${detail.document.id}`));}catch{setError('No se ha podido cambiar el estado.');}finally{setBusy(false);}}
 async function retry(){if(!detail||!canEdit(session))return;setBusy(true);setError(null);try{await apiFetch(`/api/v1/admin/documents/${detail.document.id}/ocr/retry`,{method:'POST',body:JSON.stringify({})});setMessage('Nuevo intento OCR enviado a cola.');setDetail(await apiFetch<Detail>(`/api/v1/admin/documents/${detail.document.id}`));await load();}catch(e){setError(e instanceof ApiRequestError&&e.status===409?'La versión no está subida o su integridad falló.':'No se ha podido reintentar OCR.');}finally{setBusy(false);}}
 if(auth.status==='loading'||loading)return <main className={styles.gate}>Cargando soporte documental…</main>;if(auth.status==='anonymous')return <main className={styles.gate}><div><h1>Documentos/OCR protegido</h1><GoogleSignInButton/></div></main>;if(denied)return <main className={styles.gate}>Acceso restringido.</main>;if(!session)return <main className={styles.gate}>{error}</main>;
 return <main className={styles.shell}><header className={styles.hero}><div><span>ADMIN · SOPORTE</span><h1>Documentos y OCR</h1><p>Estado global de documentos, integridad de subida y procesos OCR sin exponer texto extraído ni claves privadas.</p></div><nav><Link href="/admin/trabajos">Trabajos</Link><Link href="/admin/operaciones">Operaciones</Link><Link href="/admin">Admin</Link></nav></header>{message?<div className={styles.ok}>{message}</div>:null}{error?<div className={styles.err}>{error}</div>:null}
 <section className={styles.metrics}><article>Activos<strong>{counts.active}</strong></article><article>Archivados<strong>{counts.archived}</strong></article><article>Subida fallida<strong>{counts.upload_failed}</strong></article><article>OCR fallido<strong>{counts.ocr_failed}</strong></article><article>OCR pendiente<strong>{counts.ocr_pending}</strong></article></section>
 <section className={styles.grid}><aside className={styles.panel}><div className={styles.filters}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar título, archivo, workspace…"/><select value={ocr} onChange={e=>setOcr(e.target.value)}><option value="all">Todo OCR</option><option value="none">Sin OCR</option><option value="queued">En cola</option><option value="processing">Procesando</option><option value="succeeded">Correcto</option><option value="failed">Fallido</option></select><button onClick={()=>void load()}>Filtrar</button></div><div className={styles.list}>{docs.map(d=><button key={d.id} className={selected===d.id?styles.selected:''} onClick={()=>setSelected(d.id)}><strong>{d.title}</strong><span>{d.workspace_name} · {d.original_filename??'sin archivo'}</span><small>Subida {d.upload_status??'—'} · OCR {d.latest_ocr_status??'sin iniciar'}</small></button>)}</div></aside>
 <section className={styles.panel}>{detail?<><div className={styles.head}><div><span>{detail.document.kind}</span><h2>{detail.document.title}</h2><p>{detail.document.workspace_name} · {detail.document.original_filename}</p></div><b>{detail.document.status}</b></div><div className={styles.facts}><span>Archivo <strong>{bytes(detail.document.byte_size)}</strong></span><span>Subida <strong>{detail.document.upload_status??'—'}</strong></span><span>Integridad <strong>{detail.document.integrity_status??'—'}</strong></span><span>OCR <strong>{detail.document.latest_ocr_status??'sin iniciar'}</strong></span><span>Enlaces <strong>{detail.document.links_count}</strong></span></div>{detail.document.latest_ocr_error_code?<div className={styles.warn}><strong>{detail.document.latest_ocr_error_code}</strong><br/>{detail.document.latest_ocr_error_message}</div>:null}{canEdit(session)?<div className={styles.actions}><button disabled={busy} onClick={()=>void setStatus(detail.document.status==='active'?'archived':'active')}>{detail.document.status==='active'?'Archivar':'Restaurar'}</button><button disabled={busy||detail.document.upload_status!=='uploaded'||detail.document.integrity_status==='failed'} onClick={()=>void retry()}>Reintentar OCR</button></div>:null}<h3>Historial OCR</h3><div className={styles.rows}>{detail.ocr_runs.map(r=><div key={r.id}><strong>{r.status}</strong><span>{r.provider} · {r.error_code??'sin error'}</span></div>)}{!detail.ocr_runs.length?<p>Sin ejecuciones OCR.</p>:null}</div><h3>Extracciones</h3><div className={styles.rows}>{detail.extractions.map(r=><div key={r.id}><strong>{r.document_type}</strong><span>{r.status} · esquema v{r.schema_version}</span></div>)}{!detail.extractions.length?<p>Sin extracciones.</p>:null}</div></>:<p>Selecciona un documento.</p>}</section></section></main>;
}
