'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { useAuth } from './auth-provider';
import { GoogleSignInButton } from './google-sign-in-button';
import { businessAdminApi, type AdminBusiness } from '@/lib/business-admin-source';
import { experienceAdminApi, type BookingStatus, type ExperienceAdminCatalog, type ExperienceType } from '@/lib/business-experience-source';
import styles from './business-admin.module.css';

function slugify(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
const labels:Record<ExperienceType,string>={aove_tasting:'Cata de AOVE',mill_visit:'Visita a almazara',guided_tour:'Visita guiada',workshop:'Taller',gastronomy:'Gastronomía',nature:'Naturaleza',culture:'Cultura',family:'Familia',wellness:'Bienestar',other:'Otra'};

export function BusinessExperiencesAdmin(){
  const auth=useAuth(); const [catalog,setCatalog]=useState<ExperienceAdminCatalog|null>(null); const [businesses,setBusinesses]=useState<AdminBusiness[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null); const [denied,setDenied]=useState(false);
  const [businessId,setBusinessId]=useState(''); const [title,setTitle]=useState(''); const [slug,setSlug]=useState(''); const [summary,setSummary]=useState(''); const [experienceType,setExperienceType]=useState<ExperienceType>('aove_tasting'); const [duration,setDuration]=useState('90'); const [minParty,setMinParty]=useState('1'); const [maxParty,setMaxParty]=useState('12'); const [price,setPrice]=useState(''); const [status,setStatus]=useState<'draft'|'published'>('draft'); const [meeting,setMeeting]=useState('');
  const [slotExperience,setSlotExperience]=useState(''); const [slotStart,setSlotStart]=useState(''); const [slotEnd,setSlotEnd]=useState(''); const [capacity,setCapacity]=useState('12');
  const load=useCallback(async()=>{const [c,d]=await Promise.all([experienceAdminApi.catalog(),businessAdminApi.catalog()]);setCatalog(c);const bs=d.businesses.filter(b=>b.status==='published');setBusinesses(bs);setBusinessId(x=>x||bs[0]?.id||'');setSlotExperience(x=>x||c.experiences[0]?.id||'');},[]);
  useEffect(()=>{if(auth.status!=='authenticated')return;void load().catch((cause:unknown)=>{const s=typeof cause==='object'&&cause&&'status'in cause?Number((cause as {status?:unknown}).status):0;if(s===403)setDenied(true);else setError('No se han podido cargar las experiencias.');});},[auth.status,load]);
  async function run(task:()=>Promise<unknown>,ok:string){setBusy(true);setError(null);setMessage(null);try{await task();await load();setMessage(ok);}catch(cause){console.error(cause);setError('No se ha podido guardar el cambio.');}finally{setBusy(false);}}
  async function createExperience(){if(!businessId||!title.trim())return setError('Selecciona empresa y escribe el título.');const p=price.trim()?Math.round(Number(price.replace(',','.'))*100):null;const d=duration?Number(duration):null;const min=Number(minParty);const max=maxParty?Number(maxParty):null;if((p!==null&&!Number.isFinite(p))||!Number.isInteger(min)||(max!==null&&!Number.isInteger(max)))return setError('Revisa precio y tamaños de grupo.');await run(()=>experienceAdminApi.create(businessId,{slug:slugify(slug||title),title:title.trim(),summary:summary.trim()||null,experienceType,durationMinutes:d,minPartySize:min,maxPartySize:max,priceCents:p,meetingPointText:meeting.trim()||null,status}), 'Experiencia creada.');setTitle('');setSlug('');setSummary('');setPrice('');setStatus('draft');}
  async function createSlot(){if(!slotExperience||!slotStart)return setError('Selecciona experiencia y fecha.');const cap=Number(capacity);if(!Number.isInteger(cap)||cap<1)return setError('Aforo no válido.');await run(()=>experienceAdminApi.createSlot(slotExperience,{startsAt:new Date(slotStart).toISOString(),endsAt:slotEnd?new Date(slotEnd).toISOString():null,capacity:cap,status:'open'}),'Sesión creada.');}
  async function changeBooking(id:string,next:BookingStatus){await run(()=>experienceAdminApi.bookingStatus(id,next),`Reserva actualizada a ${next}.`);}
  const pending=useMemo(()=>catalog?.bookings.filter(b=>b.status==='pending').length??0,[catalog]);
  if(auth.status==='loading')return <main className={styles.login}><div>Comprobando acceso…</div></main>;
  if(auth.status==='anonymous')return <main className={styles.login}><div><p className={styles.eyebrow}>EXPERIENCIAS · ADMIN</p><h1>Acceso corporativo</h1><GoogleSignInButton/></div></main>;
  if(denied)return <main className={styles.login}><div><h1>Sin permisos</h1><p>Necesitas permisos de plataforma.</p></div></main>;
  if(!catalog)return <main className={styles.login}><div>Cargando experiencias…</div></main>;
  return <main className={styles.shell}>
    <header className={styles.header}><div><a href="/admin/empresas">← Empresas</a><p className={styles.eyebrow}>EXPERIENCIAS Y RESERVAS</p><h1>Marketplace territorial</h1><p>Publica actividades, abre sesiones y controla solicitudes sin superar aforo.</p></div><div className={styles.actions}><a className={styles.secondaryButton} href="/experiencias" target="_blank">Ver público ↗</a><button className={styles.secondaryButton} onClick={()=>void load()}>Actualizar</button></div></header>
    {message?<div className={styles.success}>{message}</div>:null}{error?<div className={styles.error}>{error}</div>:null}
    <section className={styles.stats}><article><strong>{catalog.experiences.length}</strong><span>Experiencias</span></article><article><strong>{catalog.experiences.filter(e=>e.status==='published').length}</strong><span>Publicadas</span></article><article><strong>{catalog.slots.filter(s=>s.status==='open').length}</strong><span>Sesiones abiertas</span></article><article><strong>{pending}</strong><span>Solicitudes pendientes</span></article></section>
    <section className={styles.layout}>
      <article className={styles.panel}><div className={styles.panelTitle}><div><h2>Nueva experiencia</h2><p>Cata, visita, taller o actividad de una empresa publicada.</p></div></div><div className={styles.formGrid}>
        <label>Empresa<select value={businessId} onChange={e=>setBusinessId(e.target.value)}>{businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>
        <label>Título<input value={title} onChange={e=>{setTitle(e.target.value);if(!slug)setSlug(slugify(e.target.value));}}/></label><label>Slug<input value={slug} onChange={e=>setSlug(slugify(e.target.value))}/></label>
        <label>Tipo<select value={experienceType} onChange={e=>setExperienceType(e.target.value as ExperienceType)}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
        <label>Duración min<input type="number" min="1" value={duration} onChange={e=>setDuration(e.target.value)}/></label><label>Grupo mínimo<input type="number" min="1" value={minParty} onChange={e=>setMinParty(e.target.value)}/></label><label>Grupo máximo<input type="number" min="1" value={maxParty} onChange={e=>setMaxParty(e.target.value)}/></label><label>Precio €/persona<input inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)}/></label>
        <label>Estado<select value={status} onChange={e=>setStatus(e.target.value as 'draft'|'published')}><option value="draft">Borrador</option><option value="published">Publicar</option></select></label><label className={styles.wide}>Punto de encuentro<input value={meeting} onChange={e=>setMeeting(e.target.value)}/></label><label className={styles.wide}>Resumen<input maxLength={400} value={summary} onChange={e=>setSummary(e.target.value)}/></label>
      </div><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>void createExperience()}>Crear experiencia</button></div></article>
      <article className={styles.panel}><div className={styles.panelTitle}><div><h2>Abrir sesión</h2><p>El aforo se controla al confirmar reservas.</p></div></div><div className={styles.formGrid}><label>Experiencia<select value={slotExperience} onChange={e=>setSlotExperience(e.target.value)}>{catalog.experiences.map(e=><option key={e.id} value={e.id}>{e.title} · {e.business_name}</option>)}</select></label><label>Inicio<input type="datetime-local" value={slotStart} onChange={e=>setSlotStart(e.target.value)}/></label><label>Fin<input type="datetime-local" value={slotEnd} onChange={e=>setSlotEnd(e.target.value)}/></label><label>Aforo<input type="number" min="1" value={capacity} onChange={e=>setCapacity(e.target.value)}/></label></div><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>void createSlot()}>Crear sesión</button></div></article>
    </section>
    <section className={styles.panel}><div className={styles.panelTitle}><div><h2>Solicitudes de reserva</h2><p>Confirmar consume aforo en transacción; nunca puede superar la capacidad publicada.</p></div></div><div className={styles.claimList}>{catalog.bookings.map(b=><article className={styles.claim} key={b.id}><div><strong>{b.experience_title} · {b.business_name}</strong><p>{b.contact_name} · {b.party_size} personas{b.contact_email?` · ${b.contact_email}`:''}</p><small>{b.slot_starts_at?new Date(b.slot_starts_at).toLocaleString('es-ES'):'Sin sesión'} · {b.status}</small></div><div className={styles.actions}>{b.status==='pending'?<><button className={styles.button} disabled={busy} onClick={()=>void changeBooking(b.id,'confirmed')}>Confirmar</button><button className={styles.dangerButton} disabled={busy} onClick={()=>void changeBooking(b.id,'declined')}>Rechazar</button></>:null}{b.status==='confirmed'?<><button className={styles.button} disabled={busy} onClick={()=>void changeBooking(b.id,'completed')}>Completada</button><button className={styles.dangerButton} disabled={busy} onClick={()=>void changeBooking(b.id,'cancelled')}>Cancelar</button></>:null}</div></article>)}</div></section>
  </main>;
}
