'use client';

import { useCallback, useEffect, useState } from 'react';
import { useAuth } from './auth-provider';
import { GoogleSignInButton } from './google-sign-in-button';
import { businessPortalApi, type MyBusiness } from '@/lib/business-portal-source';
import { myExperienceApi, type BookingStatus, type ExperienceType, type MyExperienceCatalog } from '@/lib/business-experience-source';
import styles from './business-admin.module.css';

function slugify(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
const labels:Record<ExperienceType,string>={aove_tasting:'Cata de AOVE',mill_visit:'Visita a almazara',guided_tour:'Visita guiada',workshop:'Taller',gastronomy:'Gastronomía',nature:'Naturaleza',culture:'Cultura',family:'Familia',wellness:'Bienestar',other:'Otra'};

export function MyBusinessExperiences(){
  const auth=useAuth(); const [businesses,setBusinesses]=useState<MyBusiness[]>([]); const [businessId,setBusinessId]=useState(''); const [catalog,setCatalog]=useState<MyExperienceCatalog|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null);
  const [title,setTitle]=useState('');const [slug,setSlug]=useState('');const [summary,setSummary]=useState('');const [type,setType]=useState<ExperienceType>('aove_tasting');const [duration,setDuration]=useState('90');const [price,setPrice]=useState('');const [maxParty,setMaxParty]=useState('12');const [status,setStatus]=useState<'draft'|'published'>('draft');
  const [slotExperience,setSlotExperience]=useState('');const [slotStart,setSlotStart]=useState('');const [capacity,setCapacity]=useState('12');
  const loadBusinesses=useCallback(async()=>{const payload=await businessPortalApi.list();setBusinesses(payload.businesses);setBusinessId(x=>x||payload.businesses[0]?.id||'');},[]);
  const loadCatalog=useCallback(async(id:string)=>{if(!id){setCatalog(null);return;}const c=await myExperienceApi.catalog(id);setCatalog(c);setSlotExperience(x=>c.experiences.some(e=>e.id===x)?x:c.experiences[0]?.id||'');},[]);
  useEffect(()=>{if(auth.status==='authenticated')void loadBusinesses().catch(()=>setError('No se han podido cargar tus empresas.'));},[auth.status,loadBusinesses]);
  useEffect(()=>{if(businessId)void loadCatalog(businessId).catch(()=>setError('No se han podido cargar las experiencias.'));},[businessId,loadCatalog]);
  async function run(task:()=>Promise<unknown>,ok:string){setBusy(true);setError(null);setMessage(null);try{await task();await loadCatalog(businessId);setMessage(ok);}catch(cause){console.error(cause);setError('No se ha podido guardar el cambio.');}finally{setBusy(false);}}
  async function createExperience(){if(!businessId||!title.trim())return setError('Escribe un título.');const cents=price.trim()?Math.round(Number(price.replace(',','.'))*100):null;await run(()=>myExperienceApi.create(businessId,{slug:slugify(slug||title),title:title.trim(),summary:summary.trim()||null,experienceType:type,durationMinutes:duration?Number(duration):null,maxPartySize:maxParty?Number(maxParty):null,priceCents:cents,status}), 'Experiencia creada.');setTitle('');setSlug('');setSummary('');setPrice('');}
  async function createSlot(){if(!slotExperience||!slotStart)return setError('Selecciona experiencia y fecha.');await run(()=>myExperienceApi.createSlot(businessId,slotExperience,{startsAt:new Date(slotStart).toISOString(),capacity:Number(capacity),status:'open'}),'Sesión añadida.');}
  async function booking(id:string,next:BookingStatus){await run(()=>myExperienceApi.bookingStatus(businessId,id,next),`Reserva actualizada: ${next}.`);}
  if(auth.status==='loading')return <main className={styles.login}><div>Comprobando sesión…</div></main>;
  if(auth.status==='anonymous')return <main className={styles.login}><div><p className={styles.eyebrow}>MI NEGOCIO · EXPERIENCIAS</p><h1>Inicia sesión</h1><GoogleSignInButton/></div></main>;
  if(!businesses.length)return <main className={styles.login}><div><h1>Aún no gestionas una empresa</h1><p>Reclama y verifica una ficha desde el directorio para publicar experiencias.</p><a className={styles.button} href="/explorar/empresas">Buscar mi empresa</a></div></main>;
  return <main className={styles.shell}>
    <header className={styles.header}><div><a href="/mi-negocio">← Mi negocio</a><p className={styles.eyebrow}>EXPERIENCIAS</p><h1>Actividades y reservas</h1><p>Publica experiencias y gestiona las solicitudes que llegan desde Mágina Olivo.</p></div><div className={styles.actions}><a className={styles.secondaryButton} href="/experiencias" target="_blank">Ver público ↗</a></div></header>
    {message?<div className={styles.success}>{message}</div>:null}{error?<div className={styles.error}>{error}</div>:null}
    <section className={styles.panel}><label>Empresa<select value={businessId} onChange={e=>setBusinessId(e.target.value)}>{businesses.map(b=><option key={b.id} value={b.id}>{b.name} · {b.role}</option>)}</select></label></section>
    {!catalog?<section className={styles.panel}>Cargando…</section>:<>
      <section className={styles.stats}><article><strong>{catalog.experiences.length}</strong><span>Experiencias</span></article><article><strong>{catalog.slots.filter(s=>s.status==='open').length}</strong><span>Sesiones abiertas</span></article><article><strong>{catalog.bookings.filter(b=>b.status==='pending').length}</strong><span>Pendientes</span></article><article><strong>{catalog.bookings.filter(b=>b.status==='confirmed').length}</strong><span>Confirmadas</span></article></section>
      {(catalog.role==='owner'||catalog.role==='manager'||catalog.role==='editor')?<section className={styles.layout}>
        <article className={styles.panel}><div className={styles.panelTitle}><div><h2>Nueva experiencia</h2><p>Los datos se publican bajo tu empresa; verificación y plan comercial siguen controlados por Mágina Olivo.</p></div></div><div className={styles.formGrid}><label>Título<input value={title} onChange={e=>{setTitle(e.target.value);if(!slug)setSlug(slugify(e.target.value));}}/></label><label>Slug<input value={slug} onChange={e=>setSlug(slugify(e.target.value))}/></label><label>Tipo<select value={type} onChange={e=>setType(e.target.value as ExperienceType)}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Duración min<input type="number" min="1" value={duration} onChange={e=>setDuration(e.target.value)}/></label><label>Máximo grupo<input type="number" min="1" value={maxParty} onChange={e=>setMaxParty(e.target.value)}/></label><label>Precio €/persona<input inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Estado<select value={status} onChange={e=>setStatus(e.target.value as 'draft'|'published')}><option value="draft">Borrador</option><option value="published">Publicar</option></select></label><label className={styles.wide}>Resumen<input maxLength={400} value={summary} onChange={e=>setSummary(e.target.value)}/></label></div><button className={styles.button} disabled={busy} onClick={()=>void createExperience()}>Crear experiencia</button></article>
        <article className={styles.panel}><div className={styles.panelTitle}><div><h2>Nueva sesión</h2><p>Define fecha y aforo.</p></div></div><div className={styles.formGrid}><label>Experiencia<select value={slotExperience} onChange={e=>setSlotExperience(e.target.value)}>{catalog.experiences.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label><label>Inicio<input type="datetime-local" value={slotStart} onChange={e=>setSlotStart(e.target.value)}/></label><label>Aforo<input type="number" min="1" value={capacity} onChange={e=>setCapacity(e.target.value)}/></label></div><button className={styles.button} disabled={busy} onClick={()=>void createSlot()}>Abrir sesión</button></article>
      </section>:null}
      <section className={styles.panel}><div className={styles.panelTitle}><div><h2>Reservas</h2><p>Solo owner/manager pueden decidir sobre reservas; editor publica contenido y analyst consulta.</p></div></div><div className={styles.claimList}>{catalog.bookings.map(b=><article className={styles.claim} key={b.id}><div><strong>{b.experience_title}</strong><p>{b.contact_name} · {b.party_size} personas{b.contact_email?` · ${b.contact_email}`:''}</p><small>{b.slot_starts_at?new Date(b.slot_starts_at).toLocaleString('es-ES'):'Fecha a acordar'} · {b.status}</small></div>{catalog.role==='owner'||catalog.role==='manager'?<div className={styles.actions}>{b.status==='pending'?<><button className={styles.button} disabled={busy} onClick={()=>void booking(b.id,'confirmed')}>Confirmar</button><button className={styles.dangerButton} disabled={busy} onClick={()=>void booking(b.id,'declined')}>Rechazar</button></>:null}{b.status==='confirmed'?<><button className={styles.button} disabled={busy} onClick={()=>void booking(b.id,'completed')}>Completada</button><button className={styles.dangerButton} disabled={busy} onClick={()=>void booking(b.id,'cancelled')}>Cancelar</button></>:null}</div>:null}</article>)}</div></section>
    </>}
  </main>;
}
