BEGIN;

CREATE TABLE business_offers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id UUID NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  slug TEXT NOT NULL CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  title TEXT NOT NULL,
  summary TEXT,
  description TEXT,
  offer_type TEXT NOT NULL DEFAULT 'promotion'
    CHECK (offer_type IN ('promotion','discount','fixed_price','bundle','gift','experience','seasonal')),
  original_price_cents INTEGER CHECK (original_price_cents IS NULL OR original_price_cents >= 0),
  offer_price_cents INTEGER CHECK (offer_price_cents IS NULL OR offer_price_cents >= 0),
  currency TEXT NOT NULL DEFAULT 'EUR' CHECK (currency ~ '^[A-Z]{3}$'),
  promo_code TEXT,
  redemption_mode TEXT NOT NULL DEFAULT 'contact'
    CHECK (redemption_mode IN ('contact','request','external_link','show_code')),
  redemption_url TEXT,
  terms TEXT,
  valid_from TIMESTAMPTZ,
  valid_until TIMESTAMPTZ,
  max_redemptions INTEGER CHECK (max_redemptions IS NULL OR max_redemptions > 0),
  status TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft','published','archived')),
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  updated_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  published_at TIMESTAMPTZ,
  UNIQUE (business_id, slug),
  CHECK (valid_until IS NULL OR valid_from IS NULL OR valid_until >= valid_from),
  CHECK (offer_price_cents IS NULL OR original_price_cents IS NULL OR offer_price_cents <= original_price_cents)
);

CREATE INDEX business_offers_public_idx
  ON business_offers(business_id, status, valid_until, sort_order, created_at DESC);

CREATE TABLE business_leads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id UUID NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  offer_id UUID REFERENCES business_offers(id) ON DELETE SET NULL,
  kind TEXT NOT NULL DEFAULT 'contact'
    CHECK (kind IN ('contact','quote','booking','availability','order')),
  contact_name TEXT NOT NULL,
  contact_email TEXT,
  contact_phone TEXT,
  message TEXT,
  requested_for TIMESTAMPTZ,
  party_size INTEGER CHECK (party_size IS NULL OR party_size > 0),
  source_context TEXT,
  source_key TEXT,
  status TEXT NOT NULL DEFAULT 'new'
    CHECK (status IN ('new','contacted','qualified','won','lost','spam')),
  estimated_value_cents INTEGER CHECK (estimated_value_cents IS NULL OR estimated_value_cents >= 0),
  actual_value_cents INTEGER CHECK (actual_value_cents IS NULL OR actual_value_cents >= 0),
  currency TEXT NOT NULL DEFAULT 'EUR' CHECK (currency ~ '^[A-Z]{3}$'),
  consent_business_contact BOOLEAN NOT NULL DEFAULT false,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (contact_email IS NOT NULL OR contact_phone IS NOT NULL)
);

CREATE INDEX business_leads_business_idx
  ON business_leads(business_id, status, created_at DESC);
CREATE INDEX business_leads_offer_idx
  ON business_leads(offer_id, created_at DESC) WHERE offer_id IS NOT NULL;

CREATE TABLE business_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id UUID NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  offer_id UUID REFERENCES business_offers(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL CHECK (event_type IN (
    'directory_impression','profile_view','phone_click','whatsapp_click','email_click',
    'website_click','directions_click','offer_view','offer_redeem','lead_submit'
  )),
  anonymous_id TEXT,
  source_context TEXT,
  source_key TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX business_events_business_time_idx
  ON business_events(business_id, occurred_at DESC);
CREATE INDEX business_events_type_time_idx
  ON business_events(event_type, occurred_at DESC);
CREATE INDEX business_events_offer_time_idx
  ON business_events(offer_id, occurred_at DESC) WHERE offer_id IS NOT NULL;

COMMENT ON TABLE business_events IS 'First-party attribution events for the business directory. Do not store raw IP addresses or unnecessary personal data.';
COMMENT ON TABLE business_leads IS 'User-initiated contact, quote, booking and availability requests generated by Mágina Olivo.';
COMMENT ON TABLE business_offers IS 'Time-bounded business promotions and bookable/contactable offers; payment processing is intentionally out of scope.';

COMMIT;